/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package micooc;

import org.junit.Test;
import static org.junit.Assert.*;

public class MicoocTest {
    @Test public void testSomeLibraryMethod() {
        Micooc classUnderTest = new Micooc();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
