version: 2.1

# Define the jobs we want to run for this project
jobs:
  test:
    docker:
      - image: circleci/node:15
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          working_directory: clients/micoocypress
          command: |
            pwd
            npm run test

# Orchestrate our job run sequence
workflows:
  micoocypress_test:
    jobs:
      - test