version: "3.7"
services:

  micoo-nginx:
    image: micoo-nginx:dev
    container_name: micoo-nginx
    ports:
      - "8123:80"
    volumes:
      - "../exchange:/exchange"
      - "./nginx/nginx.file-service.conf:/etc/nginx/nginx.conf"

  micoo-mongodb:
    image: mongo:4
    container_name: micoo-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mgadmin
      - MONGO_INITDB_ROOT_PASSWORD=Password1
      - MONGO_INITDB_DATABASE=micoo
    ports:
      - "27017:27017"
    volumes:
      - "database-volume:/data/db"
      - "./initializer:/docker-entrypoint-initdb.d"

volumes:
  database-volume:
